spring.application.name=PFE
server.port=8080

spring.datasource.url=jdbc:mariadb://localhost:3306/remoteflow?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci
spring.datasource.username=root
spring.datasource.password=taraji1919
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

camunda.bpm.admin-user.id=admin
camunda.bpm.admin-user.password=admin123
camunda.bpm.admin-user.firstname=Admin
camunda.bpm.admin-user.lastname=Camunda
camunda.bpm.database.schema-update=true
camunda.bpm.authorization.enabled=false
camunda.bpm.authorization.enable-default-authorizations=false
camunda.bpm.webapp.security.enabled=false
camunda.bpm.webapp.security.csrf.disabled=true
camunda.bpm.auto-deployment-enabled=true
spring.websocket.support.default.websocket=true

# Path configuration
spring.jersey.application-path=/engine-rest
camunda.bpm.webapp.enabled=true
camunda.bpm.webapp.index-redirect-enabled=true
camunda.bpm.rest.enabled=true



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sigasupport@gmail.com
spring.mail.password=kqyzalhaozmihxoi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB